module.exports = {
  brancaschulz: {name: 'Cláudia Schulz'},
  PabloCapile: {name: 'Pablo Capilé'},
  MarielleRamires: {name: 'Marielle Ramires'},
  LenissaLenza: {name: 'Lenissa LenzaCampos'},
  caroltokuyo: {name: 'carol tokuyo'},
  DriadeAguiar: {name: 'Dríade Aguiar'},
  midianinja: {name: 'Midia NINJA'},
  piravilela: {name: 'rafael vilela'},
  louakemis: {name: 'Louise Akemi'},
  TallesLopes: {name: 'Talles Lopes'},
  Irlanacassini: {name: 'Irlana Cassini' },
  edvamfilho_: {name: 'Edvam Filho' },
  claytonnobre: {name: 'Clayton Nobre' },
  biancarlima: {name: 'Bianca Lima'},
  thaneemendes: {name: 'Thanee Degasperi'},
  zasssmine: {name: 'Jasmine giovannine'},
  xaiki: {name: 'Niv Sardi'},
  uira: {name: 'Uirá Porã'},
  mariaclaudiarosel: {name: 'Maria Claudia Rossell'},
  Anapipow: {name: 'Ana Pessoa'},
  raissagalvao: {name: 'Raissa Galvão'},
  claudioprado: {name: 'Claudio Prado'},
  ivanabentes: {name: 'Ivana Bentes'},
  pamelaortizx: {name: 'Pamela Ortiz'},
  foradoeixo: {name: 'Fora do Eixo'},
  Felipe_Alten: {name: 'Felipe Altenfelder'},
  __isis__maria: {name: 'Isis Maria'},
  gian_ninja: {name: 'Gian Martins'},
  thiago_scherer: {name: 'Thiago Scherer'},
  Benja: {name: 'Benjamin'},
  odara: {name: 'Odara'},
  martina: {name: 'Martina '},
  Yumi: {name: 'Yumi '},
  Nacho: {name: 'Inacio'}
}
