module.exports = [
    {uid: 'brancaschulz', name: 'Cláudia Schulz',says:'Cadê os dados?', link: 'https://www.instagram.com/brancaschulz/'},
    {uid: 'PabloCapile', name: 'Pablo Capilé', says: 'Somos a onda!', link: 'https://www.instagram.com/pablocapile/'},
    {uid: 'MarielleRamires', name: 'Marielle Ramires',says: 'Tempo é materia prima da economia colaborativa!', link: 'https://www.instagram.com/marielleramires/'},
    {uid: 'LenissaLenza', name: 'Lenissa Lenza Campos', says:'buscando sempre a felicidade interna bruta', link: 'https://www.instagram.com/lenissalenza/'},
    {uid: 'caroltokuyo', name: 'carol tokuyo', says: 'Cultura de Red!', link: 'https://www.instagram.com/caroltokuyo/'},
    {uid: 'DriadeAguiar', name: 'Dríade Aguiar', says: 'Já falou sobre feminismo hoje?', link: 'https://www.instagram.com/driadeaguiar/'},
    {uid: 'midianinja', name: 'Midia NINJA', says: 'Baixa resolução e alta fidelidade', link: 'https://www.instagram.com/midianinja/'},
    {uid: 'piravilela', name: 'rafael vilela', says: 'desing ativista para quem não aguenta mais! Quem quer participar?', link: 'https://www.instagram.com/piravilela/'},
    {uid: 'louakemis', name: 'Louise Akemi', says: 'estamos em estado permanente de edital!', link: 'https://www.instagram.com/lou.akemi/'},
    {uid: 'TallesLopes', name: 'Talles Lopes', says: 'O Toque no Brasil é a rede social da música', link: 'https://www.instagram.com/talleslopes/'},
    {uid: 'Irlanacassini', name: 'Irlana Cassini' , says: 'vida coletiva!', link: 'https://www.instagram.com/irlanacassini/'},
    {uid: 'edvamfilho ', name: 'Edvam Filho' , says: 'Oxe!', link: 'https://www.instagram.com/edvamfilho/'},
    {uid: 'nobreclayton', name: 'Clayton Nobre' , says: 'Tamo tudo organizado pra fazer a Revolução', link: 'https://www.instagram.com/nobreclayton/'},
    {uid: 'biancarrlima', name: 'Bianca Lima', says: 'utopicamente vivendo', link: 'https://www.instagram.com/biancarrlima/'},
    {uid: 'thaneemrd', name: 'Thanee Degasperi', says: 'Fazer redes para fazer redes', link: 'https://www.instagram.com/thaneemrd/'},
    {uid: 'jasminegiovannini', name: 'Jasmine giovannine', says: 'Gandaie-se!', link: 'https://www.instagram.com/jasminegiovannini/'},
    {uid: 'xaiki', name: 'Niv Sardi', says:'É softwarelivre, caraaaaaa!', link: 'https://www.instagram.com/xaiki/'},
    {uid: 'uirapora', name: 'Uirá Porã', says: 'Vou abrir um chat no telegram', link: 'https://www.instagram.com/uirapora/'},
    {uid: 'mariaclaudiarossell', name: 'Maria Claudia Rossell', says: 'Viva Chavez!', link: 'https://www.instagram.com/mariaclaudiarossell/'},
    {uid: 'anapessoagg', name: 'Ana Pessoa', says: 'Estamos em estado permanente de documentário', link: 'https://www.instagram.com/anapessoagg/'},
    {uid: 'raissagal', name: 'Raissa Galvão', says: 'Vamos trocar a mídia de massa pela massa de mídias', link: 'https://www.instagram.com/raissagal/'},
    {uid: 'oliverninja', name: 'Oliver Kornblihtt', says:'A vida é dura senador', link: 'https://www.instagram.com/oliverninja/ '},
    {uid: 'deliriosclaudioprado', name: 'Claudio Prado', says: 'Que porra é essa?', link: 'https://www.instagram.com/deliriosclaudioprado/'},
    {uid: 'ivanabentes', name: 'Ivana Bentes', says: 'Ninjismo neles!', link: 'https://www.instagram.com/ivanabentes/'},
    {uid: 'pamelaortizx', name: 'Pamela Ortiz', says: 'Mídia NINJA é diversidade, é circular em uma infinidade de espaços...', link: 'https://www.instagram.com/pamelaortixz/'},
    {uid: 'foradoeixo', name: 'Fora do Eixo', says: 'comunidade em movimento! movimente-se', link: 'https://www.instagram.com/foradoeixo/'},
    {uid: 'felipealtenfelder', name: 'Felipe Altenfelder', says: 'estamos aqui ao vivo...', link: 'https://www.instagram.com/felipealtenfelder/'},
    {uid: 'lelecaSantos', name: 'Alessandra Santos', says: 'xepativismo!', link: 'https://www.instagram.com/lelecasantoss/'},
    {uid: '__isis__maria', name: 'Isis Maria', says: 'Que acham da gente postar esse?', link: 'https://www.instagram.com/isis_maria_/'},
    {uid: 'gian.martins.ninja', name: 'Gian Martins', says: 'e se a gente colocasse uns artistas?', link: 'https://www.instagram.com/gian.martins.ninja/'},
    {uid: 'thiago_scherer', name: 'Thiago Scherer', says: 'é verdade, pode crê!', link: 'https://www.instagram.com/thiago_scherer/'},
    {uid: 'lisa_brito', name: 'Lisa Brito', says: 'vamos nessa!', link: 'https://www.instagram.com/lisa_brito/'},
    {uid: 'Benja', name: 'Benjamin', says: 'já posso ver desenho?', link: 'https://www.instagram.com/gurizada.fde/'},
    {uid: 'Odara', name: 'Odara', says: 'tava com saudade!', link: 'https://www.instagram.com/gurizada.fde/'},
    {uid: 'Martina', name: 'Martina', says: 'você não manda em mim', link: 'https://www.instagram.com/gurizada.fde/'},
    {uid: 'Yumi', name: 'Yumi', says: 'foi o nacho!', link: 'https://www.instagram.com/gurizada.fde/'},
    {uid: 'Nacho', name: 'Inacio', says: 'foi a yumi!', link: 'https://www.instagram.com/gurizada.fde/'},
]
