module.exports = {
    brancaschulz: {name: 'Cláudia Schulz',says:'Vamos baixar um csv e fazer o relatório'}, 
    PabloCapile : {name: 'Pablo Capilé', says: 'Somos a onda'},
    MarielleRamires: {name: 'Marielle Ramires',says: 'Tempo é materia prima da economia colaborativa!'},
    LenissaLenza: {name: 'Lenissa LenzaCampos', says:'buscando sempre a felicidade interna bruta'},
    caroltokuyo:{name: 'carol tokuyo', says: 'Cultura de Red!'},
    DriadeAguiar:{name: 'Dríade Aguiar', says: 'Já falou sobre feminismo hoje?'},
    midianinja: {name: 'Midia NINJA', says: 'Baixa resolução e alta fidelidade'},
    piravilela: {name: 'rafael vilela', says: 'desing ativista para quem não aguenta mais! Quem quer participar?'},
    louakemis: {name: 'Louise Akemi', says: 'estamos em estado permanente de edital!'},
    TallesLopes: {name: 'Talles Lopes', says: 'O Toque no Brasil é a rede social da música'},
    Irlanacassini: {name: 'Irlana Cassini' , says: 'vida coletiva!'},
    edvamfilho_ : {name: 'Edvam Filho' , says: 'Oxe!'},
    claytonnobre: {name: 'Clayton Nobre' , says: 'Tamo tudo organizado pra fazer a Revolução'},
    biancarlima: {name: 'Bianca Lima', says: 'utopicamente vivendo'},
    thaneemendes: {name: 'Thanee Degasperi', says: 'o céu é o limite'},
    zasssmine: {name: 'Jasmine giovannine', says: "Gandaie-se"},
    xaiki: {name: 'Niv Sardi', says:'É softwarelivre, caraaaaaa!'}, 
    uira: {name: 'Uirá Porã', 'Vou abrir um chat no telegram'},
    mariaclaudiarosel: {name: 'Maria Claudia Rossell', says: 'Viva Chavez!'},
    Anapipow: {name: 'Ana Pessoa', says: 'Estamos em estado permanente de documentário'},
    raissagalvao: {name: 'Raissa Galvão', 'Vamos trocar a mídia de massa pela massa de mídias'},
    oliver: {name: 'Oliver Kornblihtt','A vida é dura senador'},
    claudioprado: {name: 'Claudio Prado', says: 'Que porra é essa?'},
    ivanabentes: {name: 'Ivana Bentes', says: 'Ninjismo neles!'},
    pamelaortizx: {name: 'Pamela Ortiz', says: 'Mídia NINJA é diversidade, é circular em uma infinidade de espaços...'},
    foradoeixo: {name: 'Fora do Eixo', says: 'comunidade em movimento! movimente-se'},
    Felipe_Alten: {name: 'Felipe Altenfelder', says: 'estamos aqui ao vivo...'},
    LelecaSantos: {name: 'Alessandra Santos', says: 'xepativismo!' }
    __isis__maria: {name: 'Isis Maria', says: 'Que acham da gente postar esse?'},
    gian_ninja: {name: 'Gian Martins', says: 'e se a gente colocasse uns artistas?'},
    thiago_scherer: {name: 'Thiago Scherer', says: 'é verdade, pode crê!'},
    @lisabrito: {name: 'Lisa Brito', says: 'vamos nessa!'},
    Benja: {name: 'Benjamin', says: 'já posso ver desenho?'},
    odara: {name: 'Odara', says: 'tava com saudade!'},
    martina: {name: 'Martina', says: 'você não manda em mim'},
    Yumi: {name: 'Yumi', says: 'foi o nacho!'},
    Nacho: {name: 'Inacio', says: 'foi a yumi!'},
}
